#spring中配置数据源和redis(redis不需要就不配置)
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379

#配置mybatis-plus的配置（除了数据源）
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认别名为类名）
  typeAliasesPackage: com.study.springboot_swagger2_01.pojo
  global-config:
    db-config:
      #主键类型 AUTO:“数据库ID自增”, INPUT:“用户输入ID”, ID_WORKER:“全局唯一ID (数字类型唯一ID)”, UUID:“全局唯一ID UUID”
      id-type: auto
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    #关闭缓存
    cache-enabled: false
    #配置控制台打印sql执行过程日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ftp:
  host: 192.168.0.124
  port: 22
  user: ftp-user
  password: 123456